BEGIN;

UPDATE wireframe_templates
SET sections = '[{"key":"hero","label":"Identity","width":"content","alignment":"left","emphasis":"primary","group":"identity","slots":["name","headline","location"],"required_slots":["name","headline"],"min_items":1,"max_items":1,"item_limits":{},"overflow":"show-all","fallback":"show-available"},{"key":"about","label":"Positioning","width":"content","alignment":"left","emphasis":"standard","group":"narrative","slots":["body"],"required_slots":[],"min_items":0,"max_items":1,"item_limits":{},"overflow":"condense","fallback":"collapse"},{"key":"experience","label":"Selected Proof","width":"content","alignment":"left","emphasis":"standard","group":"proof","slots":["role","company","dates","summary","highlights","outcomes"],"required_slots":["role","highlights"],"min_items":1,"max_items":2,"item_limits":{"highlights":2,"outcomes":1,"skills":0},"overflow":"rank","fallback":"raw-text"},{"key":"contact","label":"Contact","width":"content","alignment":"left","emphasis":"quiet","group":"contact","slots":["email","phone","location","links"],"required_slots":[],"min_items":0,"max_items":1,"item_limits":{"links":2},"overflow":"condense","fallback":"collapse"}]'::jsonb,
    updated_at = CURRENT_TIMESTAMP
WHERE slug = 'executive-brief';

UPDATE wireframe_templates
SET sections = '[{"key":"hero","label":"Positioning","width":"full","alignment":"left","emphasis":"primary","group":"identity","slots":["name","headline","location"],"required_slots":["name","headline"],"min_items":1,"max_items":1,"item_limits":{},"overflow":"show-all","fallback":"show-available"},{"key":"experience","label":"Featured Work","width":"full","alignment":"left","emphasis":"primary","group":"work","slots":["role","company","dates","summary","highlights","outcomes","skills"],"required_slots":["role","highlights"],"min_items":1,"max_items":4,"item_limits":{"highlights":3,"outcomes":2,"skills":4},"overflow":"condense","fallback":"raw-text"},{"key":"skills","label":"Capability Stack","width":"wide","alignment":"left","emphasis":"standard","group":"capabilities","slots":["items"],"required_slots":[],"min_items":0,"max_items":3,"item_limits":{},"overflow":"condense","fallback":"collapse"},{"key":"projects","label":"Additional Work","width":"wide","alignment":"left","emphasis":"standard","group":"work","slots":["body"],"required_slots":[],"min_items":0,"max_items":1,"item_limits":{},"overflow":"condense","fallback":"collapse"},{"key":"contact","label":"Contact","width":"full","alignment":"left","emphasis":"quiet","group":"contact","slots":["email","phone","location","links"],"required_slots":[],"min_items":0,"max_items":1,"item_limits":{"links":3},"overflow":"condense","fallback":"collapse"}]'::jsonb,
    updated_at = CURRENT_TIMESTAMP
WHERE slug = 'case-study-ledger';

UPDATE wireframe_templates
SET sections = '[{"key":"hero","label":"Identity and Proof","width":"full","alignment":"left","emphasis":"primary","group":"identity","slots":["name","headline","location","proof_facts"],"required_slots":["name","headline"],"min_items":1,"max_items":1,"item_limits":{"proof_facts":4},"overflow":"condense","fallback":"show-available"},{"key":"skills","label":"Core Competencies","width":"full","alignment":"left","emphasis":"standard","group":"capabilities","slots":["items"],"required_slots":[],"min_items":0,"max_items":4,"item_limits":{},"overflow":"condense","fallback":"collapse"},{"key":"about","label":"Featured Story","width":"wide","alignment":"left","emphasis":"standard","group":"story","slots":["body"],"required_slots":[],"min_items":0,"max_items":1,"item_limits":{},"overflow":"condense","fallback":"collapse"},{"key":"experience","label":"Professional Journey","width":"full","alignment":"left","emphasis":"primary","group":"journey","slots":["role","company","dates","summary","highlights","outcomes","skills"],"required_slots":["role"],"min_items":1,"max_items":5,"item_limits":{"highlights":3,"outcomes":2,"skills":3},"overflow":"condense","fallback":"raw-text"},{"key":"projects","label":"Achievements","width":"content","alignment":"left","emphasis":"standard","group":"proof","slots":["body"],"required_slots":[],"min_items":0,"max_items":1,"item_limits":{},"overflow":"condense","fallback":"collapse"},{"key":"education","label":"Education","width":"content","alignment":"left","emphasis":"standard","group":"credentials","slots":["body"],"required_slots":[],"min_items":0,"max_items":1,"item_limits":{},"overflow":"condense","fallback":"collapse"},{"key":"contact","label":"Contact","width":"full","alignment":"left","emphasis":"quiet","group":"contact","slots":["email","phone","location","links"],"required_slots":[],"min_items":0,"max_items":1,"item_limits":{"links":4},"overflow":"condense","fallback":"collapse"}]'::jsonb,
    updated_at = CURRENT_TIMESTAMP
WHERE slug = 'career-atlas';

COMMIT;
